### ISSUE TITLE
[Feature Request] Add Per Experience Source Multiplier 

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#38]
Currently the `experience_mult:` multiplies the same across all sources.
What do you think about the addition of per source multipliers?
Example:
```
experience_pvp_mult: 1.2
experience_pve_mult: 1.5
experience_mining_mult: 0.8

```

**Comment by NeumimTo** [comment]
I was thinking about a bit different way. 

each class or race may change exp distribution for a specific block/mob such as

```
ExperienceSources: [
     PVE: [
          <mobname>: +10
          <mobname>: -10
     ]
]
```

that might be a bit overcomplicated, on the other hand someone could find this useful.

**Comment by hellbringer616** [comment]
Would you have to define every block/mob in each class? Or just the modifier you want applied?

**Comment by NeumimTo** [comment]
Just the difference from default value

**Comment by hellbringer616** [comment]
I can think of a few ideas by having it split out already.
a skill that gives bonus XP from killing certain mobs; a "Favored Enemy" if you will
Or an archtype of a class where stats are the same, but you gain more XP from one thing and less from another.

**Comment by NeumimTo** [comment]
well a passive skill is would be another possible solution how to achieve this.

**Comment by hellbringer616** [comment]
Is there a way to implement it so it would work both ways?

Set it as a stat and set it up like a passive skill? 

Hmmm I feel like I read somewhere that your API can already do that right? Not with xp yet, but other stuff like raise ice damage.

**Comment by hellbringer616** [comment]
Yep found it here:
https://ore.spongepowered.org/NeumimTo/NT-Rpg/pages/Administrators/Classes-&-Races

```
Type: Property
    Properties: [
        {
                level: 1
                property-name: xxperience_source_creeper
                value: +10
    }
  ]
```

Am i following?

**Comment by NeumimTo** [comment]
This could be correct approach, if there would be defined exp_source_creeper property.
But...
Properties should be used *only* if you need to access its value with minimal overhead. Which means that you might need read the property's value hundred of times per second, their down side is that  have "some" memory footprint. doesnt really matter for small servers, but you could notice that if you had lots of properties and you would have 100+ players/one server, its always a tradeoff between memory usage and cpu time.

Basically if you need a some magical constant every time someone attacks someone else (which happens a lot and very frequently) properties are way to go. 

What are you suggesting here, a property for every block & entity type would be quite bad. 
So the correct sollution, as i see it, is a global effect https://ore.spongepowered.org/NeumimTo/NT-Rpg/pages/Developers/Effects-&-Attributes, or/and the configuration i posted earlier. 

I wanted just to clarify what is the purpurose of properties, since its not on the wiki yet.
